PrimaryEdLMS/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
]

core/urls.py
from django.urls import path
from . import views
from .views import (
    SubjectListView, 
    SubjectDetailView, 
    SubjectCreateView, 
    SubjectUpdateView, 
    SubjectDeleteView,
)

urlpatterns = [
    path('', views.index, name='index'),
    path("login", views.login_view, name='login'),
    path("logout", views.logout_view, name='logout'),
    path("register", views.register, name='register'),
    path('subjects/', SubjectListView.as_view(), name='subject_list'),
    path('subject/<int:pk>/', SubjectDetailView.as_view(), name='subject_detail'),
    path('subject/add/', SubjectCreateView.as_view(), name='subject_add'),
    path('subject/<int:pk>/edit/', SubjectUpdateView.as_view(), name='subject_edit'),
    path('subject/<int:pk>/delete/', SubjectDeleteView.as_view(), name='subject_delete'),
    path('forum', views.forum, name='forum'),
    path("new_post", views.new_post, name="new_post"),
    path('faq', views.faq, name='faq'),
    path('contact', views.contact, name='contact'),
    path("like/<int:post_id>", views.like_post, name="like_post"),
    path('contact/submit', views.contact_submit, name='contact_submit'),
    path('resources/', views.resource_list, name='resource_list'),
    path('resources/<int:resource_id>/', views.resource_detail, name='resource_detail'),
]

core/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    pass

class Subject(models.Model):
    subject = models.CharField(max_length=64)
    description = models.TextField(blank=True)

    def __str__(self):
        return f"{self.subject}"

class Post (models.Model):
    post = models.CharField(max_length=500)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="posts")
    timestamp = models.DateTimeField(auto_now_add=True)
    likes = models.ManyToManyField(User, blank=True, related_name="liked_posts")
    def __str__(self):
        return f"{self.user} posted {self.post} on {self.timestamp}"

class UserExtended(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

class ContactSubmission(models.Model):
    name = models.CharField(max_length=64)
    email = models.CharField(max_length=64)
    message = models.TextField(blank=True)
    submitted_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.name} sent a message: {self.message}"
    
from django.db import models

class Resource(models.Model):
    RESOURCE_TYPES = [
        ('VIDEO', 'Video'),
        ('DOC', 'Document'),
        ('QUIZ', 'Quiz'),
        # Add more types as needed
    ]
    GRADE_LEVELS = [
        ('1', 'Grade 1'),
        ('2', 'Grade 2'),
        # Add more grades as needed
    ]

    title = models.CharField(max_length=255)
    description = models.TextField()
    file_link = models.URLField(blank=True, null=True)  
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    grade_level = models.CharField(max_length=5, choices=GRADE_LEVELS)
    resource_type = models.CharField(max_length=5, choices=RESOURCE_TYPES)

    def __str__(self):
        return self.title

core/forms.py
from django import forms
from .models import Resource

class ResourceForm(forms.ModelForm):
    class Meta:
        model = Resource
        fields = ['title', 'description', 'file_link', 'subject', 'grade_level', 'resource_type']
        widgets = {
            'description': forms.Textarea(attrs={'rows': 4}),
        }

core/views.py
from .forms import ResourceForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.core.paginator import Paginator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from .models import User, Subject, Post, UserExtended, ContactSubmission, Resource

import json

# Create your views here.
def index(request):
    return render(request, 'core/index.html')

def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("index"))
        else:
            return render(request, "core/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "core/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "core/register.html", {
                "message": "Passwords must match."
            })

        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "core/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("index"))
    else:
        return render(request, "core/register.html")


class SubjectListView(ListView):
    model = Subject
    context_object_name = 'subjects'
    template_name = 'core/subject_list.html'

class SubjectDetailView(DetailView):
    model = Subject
    context_object_name = 'subject'
    template_name = 'core/subject_detail.html'

class SubjectCreateView(CreateView):
    model = Subject
    fields = ['name', 'description']
    template_name = 'core/subject_form.html'
    success_url = reverse_lazy('subject_list')

class SubjectUpdateView(UpdateView):
    model = Subject
    fields = ['name', 'description']
    template_name = 'core/subject_form.html'
    success_url = reverse_lazy('subject_list')

class SubjectDeleteView(DeleteView):
    model = Subject
    context_object_name = 'subject'
    template_name = 'core/subject_confirm_delete.html'
    success_url = reverse_lazy('subject_list')

def forum(request):
    posts_list = Post.objects.all().order_by('-timestamp')
    paginator = Paginator(posts_list, 10)

    page_number = request.GET.get('page')
    posts = paginator.get_page(page_number)

    return render(request, "core/forum.html", {"posts": posts})

def new_post(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("login"))
    elif request.method == "POST":
        content = request.POST["post_content"]
        post = Post(post=content, user=request.user)
        post.save()
        return redirect('forum')
    return render(request, 'code/forum.html')

def faq(request): 
    return render(request, 'core/faq.html')

def contact(request):
    return render(request, 'core/contact_support.html')

def like_post(request, post_id):
    if not request.user.is_authenticated:
        return JsonResponse({"error": "Login required"}, status=401)

    try:
        post = Post.objects.get(pk=post_id)
        if request.user in post.likes.all():
            post.likes.remove(request.user)
            liked = False
        else:
            post.likes.add(request.user)
            liked = True
        return JsonResponse({"likes": post.likes.count(), "liked": liked})
    except Post.DoesNotExist:
        return JsonResponse({"error": "Post not found"}, status=404)


def contact_submit(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        email = request.POST.get('email')
        message = request.POST.get('message')

        ContactSubmission.objects.create(name=name, email=email, message=message)

        # Add success message
        messages.success(request, 'Your message has been sent successfully!')

        # Render the same contact support template
        return render(request, 'core/contact_support.html')

    # If not POST request, just render the form
    return render(request, 'core/contact_support.html')

def resource_list(request):
    query = request.GET.get('query', '')
    grade_level = request.GET.get('grade_level', '')
    resource_type = request.GET.get('resource_type', '')
    
    resources = Resource.objects.all()
    if query:
        resources = resources.filter(title__icontains=query)
    if grade_level:
        resources = resources.filter(grade_level=grade_level)
    if resource_type:
        resources = resources.filter(resource_type=resource_type)

    context = {
        'resources': resources,
        'grade_levels': Resource.GRADE_LEVELS,
        'resource_types': Resource.RESOURCE_TYPES,
    }   

    return render(request, 'core/resource_list.html', context)

def resource_detail(request, resource_id):
    # Fetch the resource by ID or return 404 if not found
    resource = get_object_or_404(Resource, pk=resource_id)

    # Render the template with the resource context
    return render(request, 'core/resource_detail.html', {'resource': resource})

core/templates/core/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}PrimaryED CMS{% endblock %}</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" />
    <link rel="stylesheet" href="{% static 'core/styles.css' %}" />
    <link rel="icon" href="{% static 'core/favicon.ico' %}" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
</head>
<body>
  {% if messages %}
  {% for message in messages %}
      <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
          </button>
      </div>
  {% endfor %}
  {% endif %}

    <div class="main">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
            <a class="navbar-brand" href="{% url 'index' %}">PrimaryED CMS</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'index' %}">Home</a>
                    </li>
                    {% if request.user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'subject_list' %}">Subjects</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'resource_list' %}">Resources</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'forum' %}">Forum</a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link" href="{% url 'faq' %}">FAQ</a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link" href="{% url 'contact' %}">Contact</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                          <a class="nav-link" href="{% url 'faq' %}">FAQ</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'contact' %}">Contact</a>
                        </li>
                    {% endif %}
                </ul>
                <ul class="navbar-nav">
                    {% if request.user.is_authenticated %}
                        <li class="nav-item">
                            <span class="navbar-text mr-3">Hello, <strong>{{ request.user.username }}!</strong></span>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'login' %}">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'register' %}">Register</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </nav>

        <div class="container mt-4">{% block body %} {% endblock %}</div>
    </div> <!-- End of .main div -->

    <footer class="footer text-center py-3 small-text">
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <h5>Useful Links</h5>
                    <ul class="list-unstyled">
                        <li><a href="#">Terms & Conditions </a></li>
                        <li><a href="#">Privacy Policy</a></li>
                        <li><a href="#">Partnerships</a></li>
                        <!-- Create more links here -->
                    </ul>
                </div>
                <div class="col-md-4">
                    <h5>Help and Support</h5>
                    <ul class="list-unstyled">
                        <li><a href="{% url 'faq' %}">FAQ</a></li>
                        <li><a href="{% url 'contact' %}">Contact Support</a></li>
                        <!-- Create more links here -->
                    </ul>
                </div>
                <div class="col-md-4">
                  <h5>Follow Us</h5>
                  <div class="social-icons">
                      <a href="#" class="social-icon"><i class="fab fa-facebook-f"></i></a>
                      <a href="#" class="social-icon"><i class="fab fa-twitter"></i></a>
                      <a href="#" class="social-icon"><i class="fab fa-instagram"></i></a>
                  </div>
              </div>              
            </div>
            <div class="mt-3">
                &copy; 2023 PrimaryED CMS. All rights reserved.
            </div>
        </div>
    </footer>
    <script src="{% static 'core/index.js' %}"></script>
    <!-- Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

core/templates/core/contact_support.html
{% extends 'core/base.html' %} {% load static %} {% block body %}
<div class="container mt-4">
  <h1 class="display-4">Contact Support</h1>
  <p class="lead">
    Need help or have questions? Our team of educational wizards are here to
    assist you!
  </p>
  <hr class="my-4" />

  <div class="contact-info">
    <h3>Support Team</h3>
    <p>
      Our team of friendly educators are here to help you with any questions or
      concerns!
    </p>
    <ul>
      <li><strong>Email:</strong> info@primaryedcms.edu.au</li>
      <li><strong>Phone:</strong> +61 1234 567 890</li>
      <li>
        <strong>Address:</strong> 123 Educational Lane, Eduville, Australia
      </li>
    </ul>
  </div>

  <div class="contact-form">
    <h3>💌 Send Us a Message</h3>
    <p>
      Please fill out the form below, and our support team will get back to you
      faster than you can say "Good morning class!"
    </p>
    <form method="post" action="{% url 'contact_submit' %}">
      {% csrf_token %}
      <div class="form-group">
        <label for="name">Your Name</label>
        <input
          type="text"
          class="form-control"
          id="name"
          name="name"
          placeholder="John Doe"
        />
      </div>
      <div class="form-group">
        <label for="email">Your Email</label>
        <input
          type="email"
          class="form-control"
          id="email"
          name="email"
          placeholder="john.doe@edumail.com.au"
        />
      </div>
      <div class="form-group">
        <label for="message">Your Message</label>
        <textarea
          class="form-control"
          id="message"
          name="message"
          rows="3"
          placeholder="Please write your message here..."
        ></textarea>
      </div>
      <button type="submit" class="btn btn-primary rem2btm">
        Send Message
      </button>
    </form>
  </div>
</div>
{% endblock %}

core/templates/core/faq.html
{% extends 'core/base.html' %}

{% load static %}

{% block body %}
<div class="container mt-4">
    <h1 class="display-4">Frequently Asked Questions</h1>
    <p class="lead">Find answers to common questions about PrimaryED CMS.</p>
    <hr class="my-4">

    <div class="faq">
        <h5 class="question">Q: What types of educational resources are available in PrimaryED CMS?</h5>
        <p class="answer">A: PrimaryED CMS offers a diverse range of educational resources including interactive quizzes, detailed lesson plans, and engaging exercises tailored for primary education.</p>
    </div>

    <div class="faq">
        <h5 class="question">Q: Is PrimaryED CMS suitable for all primary education levels?</h5>
        <p class="answer">A: Yes, our platform is designed to cater to various levels of primary education, offering materials suitable for different age groups and learning stages.</p>
    </div>

    <div class="faq">
        <h5 class="question">Q: How can I access the quizzes and exercises?</h5>
        <p class="answer">A: Quizzes and exercises can be accessed by registering on our platform. Once registered, you can browse through our extensive library and select resources as per your needs.</p>
    </div>

    <div class="faq">
        <h5 class="question">Q: Can I contribute my own resources to PrimaryED CMS?</h5>
        <p class="answer">A: Absolutely! We encourage educators to contribute their own resources. Please contact us for more information on how to share your materials.</p>
    </div>

    <div class="faq">
        <h5 class="question">Q: Is there a subscription fee for using PrimaryED CMS?</h5>
        <p class="answer">A: PrimaryED CMS offers both free and premium content. While a significant portion of our resources are available free of charge, some specialised content requires a subscription.</p>
    </div>
</div>
{% endblock %}

core/templates/core/forum.html
{% extends "core/base.html" %}

{% load static %}

{% block body %}
<div class="container mt-4">
  {% if user.is_authenticated %}
  <div class="new-post mb-4">
    <form method="post" action="{% url 'new_post' %}">
      {% csrf_token %}
      <div class="form-group">
        <label for="post" class="h4">Chat Room</label>
        <textarea class="form-control" id="post" name="post_content" placeholder="What's on your mind?" rows="3"></textarea>
      </div>
      <button type="submit" class="btn btn-primary">Post</button>
    </form>
  </div>
  {% endif %}

  <div class="posts">
    {% for post in posts %}
    <div class="post card shadow mb-4">
      <div class="card-body">
        <h5 class="card-title">{{ post.user.username }}</h5>        
        <h6 class="card-subtitle mb-2 text-muted">Posted on: {{ post.timestamp }}</h6>
        <p class="card-text">{{ post.post }}</p>
        {% if user.is_authenticated %}
        <div class="like-icon">
          <span id="like-heart-{{ post.id }}" class="heart" onclick="toggleLike('{{ post.id }}')" data-liked="{% if request.user in post.likes.all %}true{% else %}false{% endif %}">
              ❤️
          </span>
          <span class="like-count">{{ post.likes.count }}</span>
        </div>
        {% endif %}
      </div>
    </div>
    {% empty %}
    <div class="alert alert-info" role="alert">No posts to display.</div>
    {% endfor %}
  </div>

  <nav aria-label="Page navigation">
    <ul class="pagination justify-content-center">
      {% if posts.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?page=1" aria-label="First">
          <span aria-hidden="true">&laquo;&laquo;</span>
        </a>
      </li>

      <li class="page-item">
        <a
          class="page-link"
          href="?page={{ posts.previous_page_number }}"
          aria-label="Previous"
        >
          <span aria-hidden="true">&laquo;</span>
        </a>
      </li>
      {% endif %}

      <li class="page-item active">
        <span class="page-link">
          Page {{ posts.number }} of {{ posts.paginator.num_pages }}
        </span>
      </li>

      {% if posts.has_next %}
      <li class="page-item">
        <a
          class="page-link"
          href="?page={{ posts.next_page_number }}"
          aria-label="Next"
        >
          <span aria-hidden="true">&raquo;</span>
        </a>
      </li>
      <li class="page-item">
        <a
          class="page-link"
          href="?page={{ posts.paginator.num_pages }}"
          aria-label="Last"
        >
          <span aria-hidden="true">&raquo;&raquo;</span>
        </a>
      </li>
      {% endif %}
    </ul>
  </nav>
</div>

{% endblock %}

core/templates/core/index.html
{% extends 'core/base.html' %}

{% load static %}

{% block body %}
<div class="jumbotron">
    <div class="row align-items-center">
        <div class="col-md-6">
            <h1 class="display-4">Welcome to PrimaryED CMS!</h1>
            <p class="lead">Your one-stop destination for educational resources, quizzes, and exercises.</p>
            <hr class="my-4">
            <p>Explore a wide range of materials designed to enhance your teaching experience.</p>
            {% if request.user.is_authenticated %}
                <a class="btn btn-primary" href="{% url 'subject_list' %}" role="button">Browse Resources</a>
            {% else %}
                <a class="btn btn-primary" href="{% url 'register' %}" role="button">Browse Resources</a>
            {% endif %}
        </div>

        <div class="col-md-6">
          <div class="image-container">
            <img src="{% static 'core/images/index_hero.jpg' %}" class="img-fluid rounded" alt="Descriptive Alt Text">
          </div>  
        </div>
    </div>
</div>
{% endblock %}

core/templates/core/login.html
{% extends "core/base.html" %}

{% block body %}

<div class="row justify-content-center">
    <div class="col-md-6">
        <div class="card mt-5">
            <div class="card-body">
                <h2 class="card-title text-center">Login</h2>

                {% if message %}
                    <div class="alert alert-danger">{{ message }}</div>
                {% endif %}

                <form action="{% url 'login' %}" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="username">Username</label>
                        <input autofocus class="form-control" id="username" type="text" name="username" placeholder="Username">
                    </div>
                    <div class="form-group">
                        <label for="password">Password</label>
                        <input class="form-control" id="password" type="password" name="password" placeholder="Password">
                    </div>
                    <input class="btn btn-primary btn-block" type="submit" value="Login">
                </form>
            </div>
        </div>
    </div>
</div>

<div class="text-center mt-3 rem2btm">
    Don't have an account? <a href="{% url 'register' %}">Register here.</a>
</div>

{% endblock %}

core/templates/core/register.html
{% extends "core/base.html" %}

{% block body %}

<div class="row justify-content-center">
    <div class="col-md-6">
        <div class="card mt-5">
            <div class="card-body">
                <h2 class="card-title text-center">Register</h2>

                {% if message %}
                    <div class="alert alert-danger">{{ message }}</div>
                {% endif %}

                <form action="{% url 'register' %}" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="username">Username</label>
                        <input class="form-control" autofocus id="username" type="text" name="username" placeholder="Username">
                    </div>
                    <div class="form-group">
                        <label for="email">Email Address</label>
                        <input class="form-control" id="email" type="email" name="email" placeholder="Email Address">
                    </div>
                    <div class="form-group">
                        <label for="password">Password</label>
                        <input class="form-control" id="password" type="password" name="password" placeholder="Password">
                    </div>
                    <div class="form-group">
                        <label for="confirmation">Confirm Password</label>
                        <input class="form-control" id="confirmation" type="password" name="confirmation" placeholder="Confirm Password">
                    </div>
                    <input class="btn btn-primary btn-block" type="submit" value="Register">
                </form>
            </div>
        </div>
    </div>
</div>

<div class="text-center mt-3 rem2btm">
    Already have an account? <a href="{% url 'login' %}">Log In here.</a>
</div>

{% endblock %}

core/templates/core/resource_detail.html
{% extends 'core/base.html' %}

{% load static %}

{% block body %}
<div class="container mt-4">
    <h1>{{ resource.title }}</h1>
    <hr>

    <div class="resource-details">
        <p><strong>Description:</strong></p>

        <p>{{ resource.description|linebreaksbr }}</p>

        {% if resource.file_link %}
            <p><strong>Cirriculum Link:</strong> <a href="{{ resource.file_link }}" target="_blank">View Resource</a></p>
        {% endif %}

        <p><strong>Grade Level:</strong> {{ resource.get_grade_level_display }}</p>
        <p><strong>Resource Type:</strong> {{ resource.get_resource_type_display }}</p>

    </div>

    <a href="{% url 'resource_list' %}" class="btn btn-primary mt-3 rem2btm">Back to Resources</a>
</div>
{% endblock %}

core/templates/core/resource_form.html
{% extends 'core/base.html' %}

{% load static %}

{% block body %}
<div class="container mt-4">
    <h1>Upload Resource</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Upload</button>
    </form>
</div>
{% endblock %}

core/templates/core/resource_list.html
{% extends 'core/base.html' %}

{% load static %}

{% block body %}

<div class="container mt-4">
    <h1>Resource Library</h1>

    <!-- Search and Filter Form -->
    <form method="get" class="mb-4">
        <div class="form-row">
            <div class="col">
                <input type="text" class="form-control" name="query" placeholder="Search resources...">
            </div>
            <div class="col">
              <select class="form-control" name="grade_level">
                  <option value="">Select Grade Level</option>
                  {% for grade in grade_levels %}
                  <option value="{{ grade.0 }}">{{ grade.1 }}</option>
                  {% endfor %}
              </select>
            </div>
            <div class="col">
              <select class="form-control" name="resource_type">
                  <option value="">Select Resource Type</option>
                  {% for type in resource_types %}
                  <option value="{{ type.0 }}">{{ type.1 }}</option>
                  {% endfor %}
              </select>
              </div>
            <div class="col">
                <button type="submit" class="btn btn-primary">Filter</button>
            </div>
        </div>
    </form>

    <!-- Resource List -->
    <div class="resource-list">
      {% for resource in resources %}
      <div class="card mb-3">
          <div class="card-body">
              <h5 class="card-title"><a href="{% url 'resource_detail' resource.id %}">{{ resource.title }}</a></h5>
              <p class="card-text">{{ resource.description|truncatewords:20 }}</p>
          </div>
      </div>
      {% empty %}
      <p>No resources found.</p>
      {% endfor %}
  </div>
</div>
{% endblock %}

core/templates/core/subject_confirm_delete.html
{% extends 'core/base.html' %}

{% block body %}
  <h2>Are you sure you want to delete "{{ object.name }}"?</h2>
  <form method="post">
    {% csrf_token %}
    <button type="submit">Yes, delete</button>
    <a href="{% url 'subject_detail' object.id %}">Cancel</a>
  </form>
{% endblock %}

core/templates/core/subject_detail.html
{% extends 'core/base.html' %}

{% block body %}
  <h2>{{ object.name }}</h2>
  <p>{{ object.description }}</p>
  <a href="{% url 'subject_update' object.id %}">Edit</a> |
  <a href="{% url 'subject_delete' object.id %}">Delete</a>
{% endblock %}

core/templates/core/subject_form.html
{% extends 'core/base.html' %}

{% block body %}
  <h2>{% if object %}Edit{% else %}Add{% endif %} Subject</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
  </form>
{% endblock %}

core/templates/core/subject_list.html
{% extends 'core/base.html' %}

{% load static %}

{% block body %}
<div class="container mt-4">
    <h1 class="display-4">Subjects</h1>
    <p class="lead">Explore our wide range of educational subjects.</p>
    <hr class="my-4">

    {% if subjects %}
    <div class="row">
        {% for subject in subjects %}
        <div class="col-md-4 mb-4">
            <div class="card h-100 d-flex flex-column">
                <div class="card-body d-flex flex-column">
                    <h5 class="card-title">{{ subject.subject }}</h5>
                    <p class="card-text flex-grow-1">{{ subject.description }}</p>
                </div>
                <div class="card-footer">
                    <a href="{% url 'resource_list' %}" class="btn btn-primary">Explore Library</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    {% else %}
    <div class="alert alert-info" role="alert">
        No subjects available.
    </div>
    {% endif %}
</div>
{% endblock %}